name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  hive: ^2.2.3
  flutter_bloc: ^8.1.6
  rive: ^0.13.9
  iconsax: ^0.0.8
  page_transition: ^2.1.0
  dio: ^5.5.0
  flutter_native_splash: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  icons_plus: ^5.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  flutter_localization: ^0.2.0
  connectivity_plus: ^6.0.3
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.1
  custom_refresh_indicator: ^4.0.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  permission_handler: ^11.3.1
  crop_your_image: ^1.1.0
  flutter_image_compress: ^2.3.0
  image: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
